/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { MealService } from "../meal.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { MealCreateInput } from "./MealCreateInput";
import { Meal } from "./Meal";
import { MealFindManyArgs } from "./MealFindManyArgs";
import { MealWhereUniqueInput } from "./MealWhereUniqueInput";
import { MealUpdateInput } from "./MealUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class MealControllerBase {
  constructor(
    protected readonly service: MealService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Meal })
  @nestAccessControl.UseRoles({
    resource: "Meal",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createMeal(@common.Body() data: MealCreateInput): Promise<Meal> {
    return await this.service.createMeal({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        mealType: true,
        name: true,
        tag: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Meal] })
  @ApiNestedQuery(MealFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Meal",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async meals(@common.Req() request: Request): Promise<Meal[]> {
    const args = plainToClass(MealFindManyArgs, request.query);
    return this.service.meals({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        mealType: true,
        name: true,
        tag: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Meal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Meal",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async meal(
    @common.Param() params: MealWhereUniqueInput
  ): Promise<Meal | null> {
    const result = await this.service.meal({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        mealType: true,
        name: true,
        tag: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Meal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Meal",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateMeal(
    @common.Param() params: MealWhereUniqueInput,
    @common.Body() data: MealUpdateInput
  ): Promise<Meal | null> {
    try {
      return await this.service.updateMeal({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          mealType: true,
          name: true,
          tag: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Meal })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Meal",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteMeal(
    @common.Param() params: MealWhereUniqueInput
  ): Promise<Meal | null> {
    try {
      return await this.service.deleteMeal({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          mealType: true,
          name: true,
          tag: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
